import type { ToolApprovalPolicy } from "@/mods/types";
import type { ToolName } from "./tool-definitions";

// Tool permissions configuration
export const TOOL_PERMISSIONS: Record<
  ToolName,
  { requiresApproval: boolean; approvalPolicy?: ToolApprovalPolicy }
> = {
  AskUserQuestion: { requiresApproval: true },
  Bash: { requiresApproval: true },
  BashOutput: { requiresApproval: false },
  TaskOutput: { requiresApproval: false },
  EnterWorktree: { requiresApproval: true },
  ExitWorktree: { requiresApproval: true },
  Edit: { requiresApproval: true },
  Glob: { requiresApproval: false },
  Grep: { requiresApproval: false },
  KillBash: { requiresApproval: true },
  TaskStop: { requiresApproval: true },
  LS: { requiresApproval: false },
  memory: { requiresApproval: false },
  memory_apply_patch: { requiresApproval: false },
  Monitor: { requiresApproval: true },
  MultiEdit: { requiresApproval: true },
  Read: { requiresApproval: false },
  read_artifact_file: { requiresApproval: false },
  ViewImage: { requiresApproval: false },
  ReadLSP: { requiresApproval: false },
  SetWorkingDirectory: { requiresApproval: false },
  SendAgentMessage: { requiresApproval: true },
  Skill: { requiresApproval: false },
  Task: { requiresApproval: true },
  TaskCreate: { requiresApproval: false },
  TaskGet: { requiresApproval: false },
  TaskList: { requiresApproval: false },
  TaskUpdate: { requiresApproval: false },
  TodoWrite: { requiresApproval: false },
  Write: { requiresApproval: true },
  write_artifact_file: { requiresApproval: false },
  shell_command: { requiresApproval: true },
  exec_command: { requiresApproval: true },
  write_stdin: { requiresApproval: false },
  shell: { requiresApproval: true },
  read_file: { requiresApproval: false },
  list_dir: { requiresApproval: false },
  grep_files: { requiresApproval: false },
  // Additional Codex tools
  ShellCommand: { requiresApproval: true },
  Shell: { requiresApproval: true },
  ReadFile: { requiresApproval: false },
  ListDir: { requiresApproval: false },
  GrepFiles: { requiresApproval: false },
  ApplyPatch: { requiresApproval: true },
  UpdatePlan: { requiresApproval: false },
};
